"use client";

import { useState, useMemo } from 'react';
import Link from 'next/link';
import { Bot, Copy, Download, Plus, Trash2, Check, ShieldAlert, Sparkles } from 'lucide-react';

const AI_BOTS = [
  'GPTBot',
  'ChatGPT-User',
  'ClaudeBot',
  'anthropic-ai',
  'CCBot',
  'PerplexityBot',
  'Google-Extended',
  'Bytespider',
];

export default function RobotsGeneratorPage() {
  const [sitemapUrl, setSitemapUrl] = useState('https://example.com/sitemap.xml');
  const [crawlDelay, setCrawlDelay] = useState('');
  const [disallowPaths, setDisallowPaths] = useState(['/admin/', '/api/', '/private/']);
  const [allowPaths, setAllowPaths] = useState(['/']);
  const [newDisallow, setNewDisallow] = useState('');
  const [newAllow, setNewAllow] = useState('');
  const [blockAiBots, setBlockAiBots] = useState(true);
  const [customBots, setCustomBots] = useState([]);
  const [copied, setCopied] = useState(false);

  const generatedRobotsTxt = useMemo(() => {
    const lines = [];

    lines.push('# robots.txt generated by OpenSourceTools');
    lines.push('# https://www.opensourcetools.online/tools/robots-generator');
    lines.push('');

    // Standard Crawlers Rule
    lines.push('User-agent: *');
    allowPaths.filter(Boolean).forEach((p) => lines.push(`Allow: ${p}`));
    disallowPaths.filter(Boolean).forEach((p) => lines.push(`Disallow: ${p}`));
    if (crawlDelay.trim()) {
      lines.push(`Crawl-delay: ${crawlDelay.trim()}`);
    }
    lines.push('');

    // AI Bots Blocking Group
    if (blockAiBots) {
      lines.push('# Block Automated AI Training Scrapers');
      AI_BOTS.forEach((bot) => {
        lines.push(`User-agent: ${bot}`);
      });
      lines.push('Disallow: /');
      lines.push('');
    }

    // Custom Bot Groups
    customBots.forEach((cb) => {
      if (cb.name.trim()) {
        lines.push(`User-agent: ${cb.name.trim()}`);
        if (cb.disallowAll) {
          lines.push('Disallow: /');
        } else {
          cb.disallows.forEach((p) => lines.push(`Disallow: ${p}`));
          cb.allows.forEach((p) => lines.push(`Allow: ${p}`));
        }
        lines.push('');
      }
    });

    // Sitemap Directive
    if (sitemapUrl.trim()) {
      lines.push(`Sitemap: ${sitemapUrl.trim()}`);
    }

    return lines.join('\n');
  }, [sitemapUrl, crawlDelay, disallowPaths, allowPaths, blockAiBots, customBots]);

  const addDisallow = (e) => {
    e.preventDefault();
    if (!newDisallow.trim()) return;
    setDisallowPaths([...disallowPaths, newDisallow.trim()]);
    setNewDisallow('');
  };

  const removeDisallow = (idx) => {
    setDisallowPaths(disallowPaths.filter((_, i) => i !== idx));
  };

  const addAllow = (e) => {
    e.preventDefault();
    if (!newAllow.trim()) return;
    setAllowPaths([...allowPaths, newAllow.trim()]);
    setNewAllow('');
  };

  const removeAllow = (idx) => {
    setAllowPaths(allowPaths.filter((_, i) => i !== idx));
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedRobotsTxt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedRobotsTxt], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <div className="tool-header">
        <h1>Robots.txt File Generator</h1>
      </div>

      <div className="tool-card" style={{ alignItems: 'stretch' }}>
        <p className="tool-description" style={{ margin: '0 auto 1.5rem', maxWidth: '750px' }}>
          Generate valid RFC 9309 compliant <code>robots.txt</code> files with custom crawl rules,
          sitemap declarations, and one-click AI scraper protection (GPTBot, ClaudeBot, CCBot).
        </p>

        {/* Builder & Output Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '1.5rem', width: '100%' }}>
          {/* Controls Column */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {/* Sitemap Field */}
            <div>
              <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.35rem' }}>
                XML Sitemap URL
              </label>
              <input
                type="url"
                className="search-input"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                placeholder="https://example.com/sitemap.xml"
                style={{ width: '100%', padding: '0.65rem 1rem', background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: '10px' }}
              />
            </div>

            {/* AI Scraper Preset Toggle */}
            <div style={{ padding: '1rem', background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: '10px' }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', fontWeight: 600, fontSize: '0.875rem' }}>
                <input
                  type="checkbox"
                  checked={blockAiBots}
                  onChange={(e) => setBlockAiBots(e.target.checked)}
                  style={{ width: '16px', height: '16px' }}
                />
                <span>Block AI Training Crawlers</span>
              </label>
              <p style={{ margin: '0.35rem 0 0', fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                Blocks GPTBot, ClaudeBot, CCBot, PerplexityBot, and Google-Extended from training on your content.
              </p>
            </div>

            {/* Disallow Paths */}
            <div>
              <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.35rem' }}>
                Disallow Paths
              </label>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.35rem', marginBottom: '0.5rem' }}>
                {disallowPaths.map((p, idx) => (
                  <span
                    key={idx}
                    style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '3px 8px', background: 'rgba(239, 68, 68, 0.1)', color: '#EF4444', border: '1px solid rgba(239, 68, 68, 0.2)', borderRadius: '6px', fontSize: '0.75rem', fontFamily: 'var(--font-mono, monospace)' }}
                  >
                    {p}
                    <button type="button" onClick={() => removeDisallow(idx)} style={{ background: 'none', border: 'none', color: 'inherit', cursor: 'pointer', padding: 0 }}>&times;</button>
                  </span>
                ))}
              </div>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <input
                  type="text"
                  value={newDisallow}
                  onChange={(e) => setNewDisallow(e.target.value)}
                  placeholder="/admin/"
                  className="search-input"
                  style={{ flex: 1, padding: '0.5rem 0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: '8px', fontSize: '0.8125rem' }}
                />
                <button type="button" onClick={addDisallow} className="lv2-pill-btn">Add</button>
              </div>
            </div>

            {/* Allow Paths */}
            <div>
              <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.35rem' }}>
                Allow Paths
              </label>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.35rem', marginBottom: '0.5rem' }}>
                {allowPaths.map((p, idx) => (
                  <span
                    key={idx}
                    style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '3px 8px', background: 'rgba(16, 185, 129, 0.1)', color: '#10B981', border: '1px solid rgba(16, 185, 129, 0.2)', borderRadius: '6px', fontSize: '0.75rem', fontFamily: 'var(--font-mono, monospace)' }}
                  >
                    {p}
                    <button type="button" onClick={() => removeAllow(idx)} style={{ background: 'none', border: 'none', color: 'inherit', cursor: 'pointer', padding: 0 }}>&times;</button>
                  </span>
                ))}
              </div>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <input
                  type="text"
                  value={newAllow}
                  onChange={(e) => setNewAllow(e.target.value)}
                  placeholder="/public/"
                  className="search-input"
                  style={{ flex: 1, padding: '0.5rem 0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: '8px', fontSize: '0.8125rem' }}
                />
                <button type="button" onClick={addAllow} className="lv2-pill-btn">Add</button>
              </div>
            </div>

            {/* Optional Crawl Delay */}
            <div>
              <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.35rem' }}>
                Crawl-Delay (Seconds, optional)
              </label>
              <input
                type="number"
                min="1"
                max="60"
                value={crawlDelay}
                onChange={(e) => setCrawlDelay(e.target.value)}
                placeholder="e.g. 10 (Supported by Bingbot & Yandex)"
                className="search-input"
                style={{ width: '100%', padding: '0.65rem 1rem', background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: '10px' }}
              />
            </div>
          </div>

          {/* Live Preview Column */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.8125rem', color: 'var(--text-secondary)' }}>
              <strong>Generated robots.txt Preview</strong>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <button
                  type="button"
                  className="lv2-pill-btn"
                  onClick={handleCopy}
                >
                  {copied ? <Check size={12} color="#10B981" /> : <Copy size={12} />} {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  type="button"
                  className="check-btn"
                  onClick={handleDownload}
                  style={{ padding: '0.35rem 0.85rem', fontSize: '0.8125rem' }}
                >
                  <Download size={13} style={{ display: 'inline', marginRight: '4px' }} /> Download .txt
                </button>
              </div>
            </div>

            <textarea
              readOnly
              value={generatedRobotsTxt}
              rows={18}
              style={{
                width: '100%',
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: '0.875rem',
                padding: '1rem',
                backgroundColor: 'var(--bg-card)',
                border: '1px solid var(--border-color)',
                borderRadius: '10px',
                resize: 'vertical',
                lineHeight: 1.55,
                color: 'var(--text-primary)',
              }}
            />
          </div>
        </div>
      </div>

      <div style={{ marginTop: '4rem' }}><Article /></div>
    </div>
  );
}

function Article() {
  return (
    <article className="tool-article">
      <h2>Robots.txt Specification &amp; RFC 9309 Rules</h2>
      <p>
        The <code>robots.txt</code> file is placed at domain apex root (e.g. <code>https://example.com/robots.txt</code>) to instruct automated web crawlers which URL directories they may request. Formalized in 2022 under <a href="https://www.rfc-editor.org/rfc/rfc9309.html" target="_blank" rel="noopener noreferrer">IETF RFC 9309</a>, it controls crawl budget efficiency and protects private server endpoints from scraper overload.
      </p>

      <h2>Core Directives &amp; Crawler Specificity Rules</h2>

      <ul>
        <li><strong>User-agent:</strong> Declares the crawler identifier (e.g. <code>User-agent: Googlebot</code> or wildcard <code>User-agent: *</code>).</li>
        <li><strong>Disallow:</strong> Specifies path prefixes that matching bots must not crawl. An empty value (<code>Disallow:</code>) allows crawling of the entire domain.</li>
        <li><strong>Allow:</strong> Explicitly permits crawling of a specific sub-path inside an otherwise disallowed directory (e.g. <code>Disallow: /blog/</code> with <code>Allow: /blog/public/</code>).</li>
        <li><strong>Sitemap:</strong> Fully-qualified absolute URL pointing to your XML sitemap index.</li>
      </ul>

      <h2>Blocking AI Scrapers vs. Preserving Search Rankings</h2>

      <p>
        AI companies deploy specialized user-agent strings specifically for model training separate from their web search crawlers:
      </p>
      <ul>
        <li><code>GPTBot</code> &amp; <code>ChatGPT-User</code> — OpenAI scraping bots. Blocking these does <strong>not</strong> affect Google or Bing search indexing.</li>
        <li><code>ClaudeBot</code> &amp; <code>anthropic-ai</code> — Anthropic AI training spiders.</li>
        <li><code>Google-Extended</code> — Google&apos;s AI training crawler (Gemini/Vertex AI). Disallowing <code>Google-Extended</code> does <strong>not</strong> stop standard <code>Googlebot</code> from indexing your pages for Google Search.</li>
      </ul>

      <h2>Technical SEO &amp; Indexation Toolkit</h2>

      <p>
        Combine robots.txt management with our full indexation diagnostic suite:
      </p>
      <ul>
        <li><strong>Live Rule Validation:</strong> Test live crawler permissions on specific URLs with our <Link href="/tools/robots-txt">Robots.txt Tester</Link>.</li>
        <li><strong>Noindex Detection:</strong> Audit on-page crawl vs indexation conflicts using our <Link href="/tools/noindex-checker">Noindex Tag Checker</Link>.</li>
        <li><strong>Sitemap Audits:</strong> Validate your XML feed structure with our <Link href="/tools/sitemap-checker">XML Sitemap Checker</Link>.</li>
      </ul>

      <h2>Frequently Asked Questions</h2>

      <h3>Does Disallow in robots.txt remove a page from Google Search?</h3>
      <p>
        No. Disallowing a URL stops search engine bots from crawling it, but if other websites link to that URL, Google can still index it as a bare URL without page snippet content. To guarantee removal, use a <Link href="/tools/noindex-checker">noindex meta tag</Link>.
      </p>

      <h3>Where must the robots.txt file be hosted?</h3>
      <p>
        It must be hosted at the exact root of your domain via HTTP/HTTPS on port 80/443 (e.g. <code>https://example.com/robots.txt</code>). Placing it in subdirectories (e.g. <code>/assets/robots.txt</code>) has no effect.
      </p>

      <h3>Does Googlebot obey Crawl-delay?</h3>
      <p>
        No. Googlebot ignores the <code>Crawl-delay</code> directive (crawl rate can be adjusted in Google Search Console). Bingbot and Yandex still respect standard <code>Crawl-delay</code> headers.
      </p>
    </article>
  );
}
