import React from 'react';
import Link from 'next/link';

export default function NoindexArticle() {
  return (
    <article className="tool-article">
      <h2>Understanding the Noindex Directive: HTML Meta vs. HTTP Headers</h2>

      <p>
        The <code>noindex</code> directive instructs search engine crawlers (such as Googlebot, Bingbot, and DuckDuckBot) to exclude a specific URL from their search index. While the concept is straightforward, improper configuration is one of the leading causes of accidental organic traffic drops and index bloat.
      </p>

      <p>
        According to <a href="https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag" target="_blank" rel="noopener noreferrer">Google Search Central documentation</a>, search engines respect <code>noindex</code> when delivered either via an HTML <code>&lt;meta&gt;</code> element in the document <code>&lt;head&gt;</code> or through an <code>X-Robots-Tag</code> HTTP response header.
      </p>

      <h2>Implementation Methods & Server Configurations</h2>

      <h3>1. HTML Meta Tag (Best for Webpages)</h3>
      <p>
        Place the tag inside the <code>&lt;head&gt;</code> section of your HTML document before the closing <code>&lt;/head&gt;</code> tag:
      </p>
      <pre className="code-pre">
        <code>{`<!-- Block all compliant search crawlers from indexing this page -->
<meta name="robots" content="noindex, follow" />

<!-- Target Googlebot specifically -->
<meta name="googlebot" content="noindex, follow" />`}</code>
      </pre>
      <p>
        <strong>Note on "follow" vs "nofollow":</strong> Using <code>noindex, follow</code> tells crawlers not to index the current URL, but to continue following links on the page to discover other pages. Using <code>noindex, nofollow</code> drops the page and ignores outbound links entirely.
      </p>

      <h3>2. X-Robots-Tag HTTP Header (Best for PDFs, Images & Global Routes)</h3>
      <p>
        Non-HTML assets (PDFs, downloadable documents, images) cannot contain HTML meta tags. To prevent these from appearing in search results, send an <code>X-Robots-Tag</code> response header from your web server.
      </p>

      <h4>Nginx Configuration</h4>
      <pre className="code-pre">
        <code>{`# Block indexing on all PDF downloads
location ~* \\.pdf$ {
    add_header X-Robots-Tag "noindex, nofollow";
}

# Block indexing on an entire staging subdomain
server {
    server_name staging.example.com;
    add_header X-Robots-Tag "noindex, nofollow";
    # ...
}`}</code>
      </pre>

      <h4>Apache (.htaccess) Configuration</h4>
      <pre className="code-pre">
        <code>{`# Add noindex header to private directories or file types
<FilesMatch "\\.(pdf|doc|docx)$">
    Header set X-Robots-Tag "noindex, nofollow"
</FilesMatch>`}</code>
      </pre>

      <h4>Next.js (App Router / Pages Router) Headers</h4>
      <pre className="code-pre">
        <code>{`// next.config.js / next.config.mjs
export default {
  async headers() {
    return [
      {
        source: '/admin/:path*',
        headers: [
          { key: 'X-Robots-Tag', value: 'noindex, nofollow' },
        ],
      },
    ];
  },
};`}</code>
      </pre>

      <h2>Critical Technical Trap: Robots.txt vs. Noindex</h2>

      <p>
        The single most common indexation mistake is simultaneously blocking a page in <code>robots.txt</code> and applying a <code>noindex</code> tag.
      </p>

      <ul>
        <li>
          <strong>Robots.txt controls crawl access:</strong> A <code>Disallow</code> rule tells crawlers not to request the URL.
        </li>
        <li>
          <strong>Noindex controls indexation:</strong> A <code>noindex</code> directive tells crawlers not to list the URL in search results.
        </li>
      </ul>

      <p>
        If Googlebot is disallowed by <Link href="/tools/robots-txt">robots.txt</Link> from fetching a page, it <em>never downloads the HTML or response headers</em>. Consequently, it cannot read the <code>noindex</code> directive. If external websites link to that URL, Google may still index the bare URL without snippet text.
      </p>
      <p>
        <strong>Rule:</strong> To remove an already-indexed URL via <code>noindex</code>, the URL <em>must be crawlable</em> (allowed in robots.txt) so Googlebot can fetch it and process the directive.
      </p>

      <h2>Common Scenarios for Noindex Usage</h2>

      <ul>
        <li><strong>Staging & Preview Environments:</strong> Prevent pre-production environments from competing with live canonical pages.</li>
        <li><strong>Internal Search Results:</strong> Prevent crawl waste and low-quality duplicate pages generated by user search queries.</li>
        <li><strong>Admin, Login & Account Dashboards:</strong> Keep gated portals and user account endpoints out of public search results.</li>
        <li><strong>Thank-You & Conversion Pages:</strong> Prevent users from landing directly on post-conversion URLs from organic search.</li>
        <li><strong>Faceted Filters with Low Search Demand:</strong> In e-commerce, combine <Link href="/tools/canonical-url">Canonical URLs</Link> or noindex on multi-attribute filter matrices.</li>
      </ul>

      <h2>Frequently Asked Questions</h2>

      <h3>How long does it take for Google to remove a noindexed page?</h3>
      <p>
        Google removes a page once Googlebot recrawls the URL and parses the <code>noindex</code> directive. For frequently crawled pages, this typically takes 1 to 5 days. For low-priority pages, it can take several weeks. To expedite removal, request indexing in Google Search Console or use the temporary Removals tool.
      </p>

      <h3>Does a noindexed page pass PageRank through its links?</h3>
      <p>
        If configured with <code>noindex, follow</code>, search engines will initially crawl outbound links and pass ranking equity. However, Google has stated that long-term noindexed pages eventually behave identically to <code>noindex, nofollow</code> as the page is crawled less frequently over time.
      </p>

      <h3>What is the difference between noindex and canonical tags?</h3>
      <p>
        A <code>noindex</code> tag tells search engines to completely exclude a page from the index. A <Link href="/tools/canonical-url">canonical tag</Link> specifies the primary master version among duplicate or similar pages, consolidating link equity rather than excluding the content topic. Never place a cross-domain canonical and a noindex tag on the same page, as they send contradictory signals.
      </p>
    </article>
  );
}